- name: Generate BNG ACL
  hosts: BBPEs
  connection: local
  gather_facts: True
  pre_tasks:
    - include_vars: objects/subscribers.yml
    - include_vars: objects/services.yml
    - include_vars: objects/hosts.yml
    - include_vars: objects/hostgroups.yml
    - include_vars: ACLs/example_ACL.yml
  roles:
    - BNG
