---
cdns1_bllon:
  hostname: cdns1.bllon
  ip: 192.168.0.10
  description: "Customer DNS 1"
  site: bllon

cdns2_bllon:
  hostname: cdns2.bllon
  ip: 192.168.0.11
  description: "Customer DNS 2"
  site: bllon
...
