---
service_any:
  proto: any
  sport: any
  dport: any

service_ssh:
  proto: tcp
  sport: any
  dport: 22

service_telnet:
  proto: tcp
  sport: any
  dport: 23

service_dns:
  proto: udp
  sport: any
  dport: 53

service_dnsxfer:
  proto: tcp
  sport: any
  dport: 53
...
